### ISSUE TITLE
import failures in example code

### ISSUE THREAD

**Issue by oxrock** [samuelpmish/RLUtilities#15]
examples/0_Ball_Prediction.py 
"""
from RLUtilities.GameInfo import GameInfo
from RLUtilities.Simulation import Ball, Field
from RLUtilities.LinearAlgebra import vec3
"""
RLU is capitalized despite imports being case sensitive, thus causing imports in this example script to fail.  Even if you correct to "rlutilities.GameInfo", the GameInfo directory does not currently exist within this repository.

**Comment by samuelpmish** [comment]
There's a few other similar issues that slipped through after the recent breaking API changes. These are fixed on my end, and will be part of the next release. Sorry for the confusion in the meantime.

**Comment by samuelpmish** [comment]
see https://github.com/samuelpmish/RLUtilities/pull/16

**Comment by samuelpmish** [comment]
thanks, Kip!
