### ISSUE TITLE
halp

### ISSUE THREAD

**Issue by haxerman1** [samuelpmish/RLUtilities#42]
from blind_and_deaf.bot import Blind_and_Deaf
  File "C:\Users\Veni_._\Downloads\venybot\rlmarlbot\blind_and_deaf\bot.py", line 9, in <module>
    from rlutilities.simulation import Game
ModuleNotFoundError: No module named 'rlutilities'
PS C:\Users\Veni_._\Downloads\venybot> pip install rlutilities
Requirement already satisfied: rlutilities in c:\users\veni_._\appdata\local\programs\python\python311\lib\site-packages (0.0.13)
PS C:\Users\Veni_._\

can someone help me with this?

**Comment by samuelpmish** [comment]
hey, this project hasn't been actively maintained for years, so I'm afraid you're mostly on your own here.

One thing you might check is that you're running your bot with the same version of python associated with `pip` used to install rlutilities. You may have more luck asking questions at the RLBot discord channel, good luck.
